# Generated by Django 3.1.7 on 2021-03-23 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=10000)),
                ('status', models.CharField(choices=[('NE', 'New'), ('OP', 'Open'), ('CL', 'Closed'), ('IP', 'In Progress'), ('IT', 'In Testing')], default='NE', max_length=20)),
                ('datetime_opened', models.DateTimeField(auto_now_add=True)),
                ('datetime_last_modified', models.DateTimeField(auto_now=True)),
                ('datetime_closed', models.DateTimeField()),
                ('priority', models.CharField(choices=[('HT', 'Highest'), ('HR', 'Higher'), ('NO', 'Normal'), ('LR', 'Lower'), ('LT', 'Lowest')], default='NO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VersionUnderTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('issue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ripa.issue')),
                ('escaped', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=4)),
            ],
            bases=('ripa.issue',),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('issue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ripa.issue')),
            ],
            bases=('ripa.issue',),
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ripa.project'),
        ),
    ]
