# Generated by Django 3.1.7 on 2021-03-23 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ripa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('issue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ripa.issue')),
            ],
            bases=('ripa.issue',),
        ),
        migrations.AddField(
            model_name='issue',
            name='datetime_closed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='datetime_opened',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
