# Generated by Django 3.1.7 on 2021-03-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ripa', '0002_auto_20210323_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='datetime_last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='datetime_closed',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='datetime_opened',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
