# Generated by Django 3.1.7 on 2021-03-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ripa', '0003_auto_20210323_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('NE', 'New'), ('OP', 'Open'), ('CL', 'Closed'), ('IP', 'In Progress'), ('IT', 'In Testing')], default='NE', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
