# Generated by Django 3.1.7 on 2021-03-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ripa', '0004_auto_20210323_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='escaped',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=4),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('HT', 'Highest'), ('HR', 'Higher'), ('NO', 'Normal'), ('LR', 'Lower'), ('LT', 'Lowest')], default='Normal', max_length=20),
        ),
    ]
