# Generated by Django 3.1.7 on 2021-03-23 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ripa', '0005_auto_20210323_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('issue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ripa.issue')),
            ],
            bases=('ripa.issue',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('HT', 'Highest'), ('HR', 'Higher'), ('NO', 'Normal'), ('LR', 'Lower'), ('LT', 'Lowest')], default='NO', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ripa.project'),
        ),
    ]
